name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build project
      run: cargo build --release

    - name: Install cargo-deb
      run: cargo install cargo-deb

    - name: Package as deb
      run: cargo deb

    # Option 1: If you want to upload as a regular artifact
    - name: Upload deb package
      uses: actions/upload-artifact@v4
      with:
        name: file-explorer-deb
        path: ./target/debian/*.deb
